version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=koalixcrm

  web:
    image: ghcr.io/koalixswitzerland/koalixcrm-prod-container:main
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=koalixcrm
      - SQL_USER=postgres
      - SQL_PASSWORD=password
      - SQL_HOST=db
      - SQL_PORT=5432
      - SECRET_KEY=SECRETKEYOFYOURCHOICE
      - DJANGO_ALLOWED_HOSTS=localhost 0.0.0.0 127.0.0.1
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - web

volumes:
  postgres_data: {}
  static_volume: {}
  media_volume: {}