version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=koalixcrm

  web:
    image: ghcr.io/koalixswitzerland/koalixcrm-prod-container:main
    ports:
      - "8000:8000"
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=koalixcrm
      - SQL_USER=postgres
      - SQL_PASSWORD=password
      - SQL_HOST=db
      - SQL_PORT=5432
      - SECRET_KEY=SECRETKEYOFYOURCHOICE
      - DJANGO_ALLOWED_HOSTS=localhost 0.0.0.0
    depends_on:
      - db
volumes:
  postgres_data: {}